export const ADD_MOVIE_TO_WATCHEDLIST = "ADD_MOVIE_TO_WATCHEDLIST";
export const REMOVE_MOVIE_TO_WATCHEDLIST = "REMOVE_MOVIE_TO_WATCHEDLIST";
export const ADD_MOVIE_TO_WATCHED = "ADD_MOVIE_TO_WATCHED";
export const REMOVE_MOVIE_TO_WATCHED = "REMOVE_MOVIE_TO_WATCHED";
export const MOVIE_TO_WATCHEDLIST = "MOVIE_TO_WATCHEDLIST";
